#uncomment to do profiling
# for profiling https://esham.io/2018/02/zsh-profiling
#zmodload zsh/datetime
#setopt PROMPT_SUBST
#PS4='+$EPOCHREALTIME %N:%i> '

#logfile=$(mktemp zsh_profile.XXXXXXXX)
#echo "Logging to $logfile"
#exec 3>&2 2>$logfile
#setopt XTRACE
#uncomment to do profiling

# Make aliases available to vim
# https://stackoverflow.com/questions/8841116/vim-not-recognizing-aliases-when-in-interactive-mode
# https://stackoverflow.com/questions/23258413/expand-aliases-in-non-interactive-shells
setopt aliases

# https://stevenvanbael.com/profiling-zsh-startup
#zmodload zsh/zprof

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

GOPATH="$HOME/go"
export GOPATH

#COMPOSER_HOME="/composer"
#export COMPOSER_HOME

# Directories to be prepended to $PATH
declare -a dirs_to_prepend
dirs_to_prepend=(
  "/opt/homebrew/opt/mysql-client/bin"
  "/opt/homebrew/bin"
  "/usr/local/bin"
  "/usr/local/go/bin"
  "/usr/bin"
  "/usr/local/sbin"
  "/usr/local/git/bin"
  "/usr/local"
  "/usr/local/mysql/bin"
  "/usr/local/Cellar/mysql@5.7/5.7.25/bin/"
  "/sw/bin/"
  "$HOME/dotfiles/bin"
  "$HOME/code/apiabroad-utils"
  "$HOME/code/apiabroad-utils/bin"
  "$HOME/code/scripts"
  "$HOME/.composer/vendor/bin"
  "$HOME/bin"
  "$HOME/.yarn/bin"
  "/usr/local/opt/coreutils/libexec/gnubin" # Add brew-installed GNU core utilities bin
  "$GOPATH/bin"
  "/Applications/Postgres.app/Contents/Versions/latest/bin"
  "$HOME/.local/bin"
  "/usr/local/opt/mysql-client/bin"
  "/opt/homebrew/bin"
  "/opt/homebrew/sbin"
  "$HOME/.cargo/bin"
)

# Explicitly configured $PATH
PATH="/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="nick"

# Z beats cd most of the time
# . ~/z/z.sh

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=$HOME/dotfiles/zsh

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew catimg node npm history ssh-agent vi-mode zsh-autosuggestions zsh-syntax-highlighting z asdf git-trim)

# User configuration

source $ZSH/oh-my-zsh.sh

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# Automatically list directory contents on `cd`.
# auto-ls () {
#   emulate -L zsh;
#   # explicit sexy ls'ing as aliases arent honored in here.
#   hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -aFh --color --group-directories-first || ls
# }
# chpwd_functions=( auto-ls $chpwd_functions )


# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

export EDITOR=/usr/bin/vim

# [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc

# Turn off autocorrection
unsetopt correct_all
unsetopt correct

# pet cli snippet manager stuff
function prev() {
  PREV=$(fc -lrn | head -n 1)
  sh -c "pet new `printf %q "$PREV"`"
}

function pet-select() {
  BUFFER=$(pet search --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N pet-select
bindkey '^s' pet-select

# load zmv shell cmd
autoload zmv
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"


# Set cdpath; from https://twitter.com/paulredmond/status/1204557648026144768
cdpath=(~/sites ~/homestead-sites/segmetrics)

# Commenting out for now to see if this is extraneous
# autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /usr/local/bin/bit bit
#

# Speeds up load time
DISABLE_UPDATE_PROMPT=true

# Perform compinit only once a day.
autoload -Uz compinit

setopt EXTENDEDGLOB
for dump in $ZSH_COMPDUMP(#qN.m1); do
  compinit
  if [[ -s "$dump" && (! -s "$dump.zwc" || "$dump" -nt "$dump.zwc") ]]; then
    zcompile "$dump"
  fi
  echo "Initializing Completions..."
done
unsetopt EXTENDEDGLOB
compinit -C

source /Users/travis/.config/broot/launcher/bash/br

#compdef gt
###-begin-gt-completions-###
#
# yargs command completion script
#
# Installation: gt completion >> ~/.zshrc
#    or gt completion >> ~/.zprofile on OSX.
#
_gt_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" gt --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _gt_yargs_completions gt
###-end-gt-completions-###

# 1Password CLI stuff
OP_BIOMETRIC_UNLOCK_ENABLED=true

# disable pyenv stuff for now to speed up shell
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init -)"

eval "$(atuin init zsh)"

# For mods cli tool https://github.com/charmbracelet/mods/tree/23724d3d65933ad5af553f5e5567c6763d1b77eb#openai
export OPENAI_API_KEY=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

# for bat theme https://github.com/sharkdp/bat#customization
export BAT_THEME="ansi"


# fnm
export PATH="/Users/travis/Library/Application Support/fnm:$PATH"
eval "`fnm env --use-on-cd`"


source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

#uncomment to do profiling
#unsetopt XTRACE
#exec 2>&3 3>&-
#uncomment to do profiling
#

