# Run `brew bundle -v --file=~/Brewfile`

cask_args appdir: '/Applications'

cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'sequel-pro'
cask 'flux'
cask 'alfred'
cask 'atext'
cask 'dropbox'
cask 'skype'
cask 'macdown'
cask 'imageoptim'
cask 'spotify'
cask 'caprine'
cask 'firefox'
cask 'tomighty'
cask 'gitup'
cask 'qlmarkdown'
cask 'keepingyouawake'
cask 'insomnia'
cask 'db-browser-for-sqlite'
cask 'mosaic'
cask 'logitech-camera-settings'
cask 'install font-hack-nerd-font'

brew 'mas'
brew 'zsh'
brew 'git'
brew 'openssl'
brew 'npm'
brew 'node'
brew 'ack'
brew 'nginx'
brew 'imagemagick'
brew 'ffmpeg'
brew 'wget'
brew 'youtube-dl'
brew 'mpv'
brew 'ghi'
brew 'nmap'
brew 'phpunit'
brew 'gpg'
brew 'whois'
brew 'rbenv'
brew 'ruby-build'
brew 'lame'
brew 'figlet'
brew 'imagesnap'
brew 'sl'
brew 'the_silver_searcher'
brew 'autojump'
brew 'yarn'
brew 'cputhrottle'
brew 'exa'
brew 'bat'
brew 'prettyping'
brew 'fzf'
brew 'fd'
brew 'github/gh/gh'
brew 'lsd'
brew 'diff-so-fancy'
brew 'jq'
brew 'tree'
brew 'pv'

mas 'Fantastical 2 - Calendar and Reminders', id: 975937182
mas '1Password 7 - Password Manager', id: 1333542190
mas 'Shush - Microphone Manager', id: 496437906 
mas 'Harvest', id: 506189836
mas 'iA Writer', id: 775737590
mas 'Shush - Microphone Manager', id: 496437906
