set nocompatible
filetype on
filetype off

" Show current mode at the bottom
set showmode

" Show a line under the line the cursor is on
set cursorline

" Statusline settings
set laststatus=2 " Enable statusline

set statusline=
" set statusline=%{fugitive#statusline()} " Add git status from vim-fugitive plugin
set statusline=%t		"tail of the filename
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

syntax on

" Show line numbers
set number

" Show relative line numbers
set relativenumber

" No swap files or backup files!
set nobackup
set noswapfile

" Search settings
set ignorecase " ignore case when searching
set	smartcase " ignore case if search pattern is all lowercase, case-sensitive otherwise
set incsearch
set showmatch
set hlsearch

set history=1000
set undolevels=1000
set title
set visualbell
set noerrorbells

" Mappings

" Change the mapleader from \ to ,
let mapleader=","

" Unhighlight search results
nnoremap <leader><space> :noh<cr>

" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" Format JSON files with jq
nmap <leader>jq :%!jq .<CR>

" Show a colored column
" set colorcolumn=85

set mouse=a

" Make backspace work as expected
" https://vi.stackexchange.com/a/2163
set backspace=indent,eol,start
set ruler

" Tab settings
" from https://stackoverflow.com/a/234578/158449
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab


" Saved macros!
let @z = 'vwwhdAa pj0'
let @x = 'iphp artisan employee:create --email=wwwwwwwwi--password= €kb(PASS€kb€kb€kb€kb€kbPASSWORD €kb --name=wwi--last-name=j0'
let @c = 'vf=x€ýaf-vf=xwhd$j0'

" Make aliases work in vim
" https://stackoverflow.com/questions/8841116/vim-not-recognizing-aliases-when-in-interactive-mode
let $BASH_ENV = "~/dotfiles/shell/shell_aliases"
