# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ";tmail"
    replace: "travis@travisnorthcutt.com"
  - trigger: ";mail"
    replace: "travis.northcutt@apiabroad.com"
  - trigger: ";tcom"
    replace: "travisnorthcutt.com"
  - trigger: ";todo"
    replace: "- [ ] #task"

  - trigger: ";task"
    replace: "- [ ] #task"

  - trigger: ";cmd"
    replace: "⌘"

  # Coding
  - trigger: ";cl"
    replace: "console.log("

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Work emails
  - trigger: ";scarlett"
    replace: "soropeza@artedigital-mx.com"
  - trigger: ";josue"
    replace: "lperez@artedigital-mx.com"
  - trigger: ";yobhani"
    replace: "amartinez@artedigital-mx.com"
  - trigger: ";leo"
    replace: "mpereira@daitan.com"
  - trigger: ";lucas"
    replace: "lucas.vale@encora.com"
