#!/bin/sh
# .git/hooks/ctags >/dev/null 2>&1 &
### lolcommits hook (begin) ###
if [ ! -d "$GIT_DIR/rebase-merge" ]; then
export LANG="en_US"
lolcommits --capture --fork
fi
###  lolcommits hook (end)  ###
